=============================================================================
                                Iniphile/PHP
=============================================================================
-----------------------------------------------------------------------------
                    PHP binding for the Iniphile library
-----------------------------------------------------------------------------

:Author: Roman Neuhauser
:Contact: neuhauser@sigpipe.cz
:Copyright: This document is in the public domain.

.. contents::

Introduction
============

Iniphile/PHP is a PHP_ binding for the Iniphile_ library.  It is known to work
with PHP 5.2.11, 5.2.12, 5.3.1 and 5.3.2 on FreeBSD 9, and on Windows XP with
Visual Studio 9.

.. _PHP: http://www.php.net/
.. _Iniphile: http://codex.sigpipe.cz/iniphile/


Prerequisities
==============

* PHP 5.2 or 5.3
* C++ compiler (gcc-4.2 or higher; MSVC 9)


Reference
=========

INI file syntax
+++++++++++++++

See the `INI file syntax`_ section in the Iniphile documentation.

.. _INI file syntax: http://codex.sigpipe.cz/iniphile/#ini-file-syntax


class iniphile
++++++++++++++

::

  class iniphile
  {
      __construct(string $path);
      array  get(string $query, array  $default);
      bool   get(string $query, bool   $default);
      float  get(string $query, float  $default);
      int    get(string $query, int    $default);
      string get(string $query, string $default);
  }

iniphile::__construct
~~~~~~~~~~~~~~~~~~~~~

``iniphile::__construct`` takes a single argument, a file ``$path``.  Upon
successful completion, ``$path`` has been parsed.  Throws ``iniphile_error``
if ``$path`` doesn't exist or if it's not an INI file.

iniphile::get
~~~~~~~~~~~~~

``iniphile::get`` takes two arguments, string ``$query``, and ``$default``
which may be ``array`` ``bool``, ``float``, ``int``, ``string`` (or an object
which implements the ``__toString`` method) or.  It returns a value of the
same type as the second argument.

Throws ``iniphile_error`` if called with a wrong number of arguments or if
the second argument isn't of one of the allowed types.

See the Iniphile documentation for a complete description of
`iniphile::get<T>`_.

.. _iniphile::get<T>:
   http://codex.sigpipe.cz/iniphile/#t-get-t-ast-node-std-string-t



Downloads
=========

Repository
++++++++++

The latest source can be checked out from the Mercurial_ repository_.

.. _Mercurial: http://selenic.com/mercurial/
.. _repository: https://hg.sigpipe.cz/

Official tarballs
+++++++++++++++++

All Iniphile/PHP releases can be found in the `download directory`_.

.. _download directory: http://codex.sigpipe.cz/php-iniphile/dist/


.. target-notes::
.. section-numbering::

.. vim: ft=rst sts=2 sw=2 tw=77
